const params=new URLSearchParams(location.search);const skeptical=params.get("mode")==="sceptique";
let step=0;
const data=[
{kick:"01 · LE PROBLÈME",title:"Voici Amina.",text:"19 ans. Elle a participé à des formations, des activités et des projets. Elle cherche aujourd'hui une nouvelle opportunité.",card:`<div class="person-line"><div class="initial">A</div><div><b>Amina N.</b><div class="muted">19 ans · Yaoundé</div></div></div><p>Elle possède un CV et plusieurs certificats.</p>`,q:"Mais que peut-on réellement comprendre de ses capacités à partir de ces seuls éléments ?"},
{kick:"02 · UN DÉFI RÉEL",title:"On lui confie une situation.",text:"Organiser une journée d'information pour 40 jeunes.",card:`<h3>Défi : coordonner une activité communautaire</h3><p>Objectif : préparer, mobiliser et conduire l'activité, puis produire un compte rendu.</p><div class="criteria"><div><span>Planifier les tâches</span><b>critère</b></div><div><span>Mobiliser les participants</span><b>critère</b></div><div><span>Gérer les imprévus</span><b>critère</b></div><div><span>Produire un compte rendu</span><b>critère</b></div></div>`,q:"Ce n'est pas un examen. Amina peut réussir, échouer et recommencer."},
{kick:"03 · L'ÉCHEC",title:"La première tentative ne suffit pas.",text:"18 personnes seulement participent. Plusieurs tâches ont été mal réparties.",card:`<div class="notice"><b>Première tentative</b><br>Les critères ne sont pas tous satisfaits.</div><div class="story-question">Que fait CDS de cet échec ?</div>`,q:"Il ne devient pas une note publique. Il peut simplement faire partie du parcours d'apprentissage."},
{kick:"04 · LA RÉALISATION",title:"Amina recommence.",text:"Cette fois, 43 participants sont présents. Les tâches sont réparties et le compte rendu est produit.",card:`<h3>Réalisation</h3><div class="criteria"><div><span>Planification</span><b>réalisée</b></div><div><span>Mobilisation</span><b>réalisée</b></div><div><span>Gestion des imprévus</span><b>réalisée</b></div><div><span>Compte rendu</span><b>produit</b></div></div>`,q:"La question devient : comment rendre cette réalisation vérifiable ?"},
{kick:"05 · LA PREUVE",title:"La réalisation laisse des traces.",text:"Un compte rendu, un planning, des éléments de l'activité et le récit de ce qui a été fait permettent de documenter l'expérience.",card:`<div class="criteria"><div><span>Compte rendu</span><b>document</b></div><div><span>Planning</span><b>document</b></div><div><span>Activité</span><b>trace</b></div><div><span>Contexte</span><b>décrit</b></div></div>`,q:"Mais une personne peut toujours déclarer qu'elle a fait quelque chose. Qui peut en témoigner ?"},
{kick:"06 · LE TÉMOIGNAGE",title:"Paul intervient.",text:"Paul a accompagné Amina. Il reçoit uniquement les informations nécessaires à la vérification de cette réalisation.",card:`<div class="story-card"><h3>Demande de témoignage</h3><p><b>Défi :</b> coordonner une activité communautaire</p><p><b>Demande :</b> confirmer si les critères ont effectivement été satisfaits.</p><div class="story-question">Paul peut confirmer, ou ne pas confirmer en motivant son choix.</div></div>`,q:"La confiance ne vient donc pas de CDS lui-même : elle vient d'une relation réelle que CDS rend traçable."},
{kick:"07 · LA RECONNAISSANCE",title:"Une capacité peut maintenant être reconnue.",text:"Pas de score. Pas de classement. Une reconnaissance contextualisée.",card:`<div class="success"><b>Organisation — Confirmée</b><br>Contexte : coordination d'une activité communautaire<br><span>Source : Paul · réalisation documentée</span></div><p>La personne conserve le contrôle de la diffusion de cette reconnaissance.</p>`,q:"Un partenaire peut maintenant comprendre davantage qu'une simple déclaration sur un CV."},
{kick:"08 · LE TEST",title:skeptical?"Maintenant, challengez l'idée.":"Maintenant, changeons de point de vue.",text:skeptical?"Vous pouvez remettre en question chaque étape. Les objections font partie de la démonstration.":"Une entreprise reçoit un accès limité à ce qu'Amina choisit de partager.",card:`<div class="criteria"><div><span>Entreprise X voit</span><b>partagé</b></div><div><span>Elle peut vérifier</span><b>contexte</b></div><div><span>Elle ne voit pas</span><b>carnet privé</b></div><div><span>Elle peut proposer</span><b>opportunité</b></div></div>`,q:skeptical?"Questions critiques : qui vérifie ? pourquoi pas un CV numérique ? comment protéger la personne ? où cette infrastructure crée-t-elle réellement de la valeur ?":"Amina peut désormais partager cette partie de son parcours avec une personne ou une organisation de son choix."}
];
function render(){const d=data[step];document.getElementById("counter").textContent=String(step+1).padStart(2,"0")+" / 08";document.getElementById("story").innerHTML=`<section class="story-stage"><div class="story-kicker">${d.kick}</div><h1>${d.title}</h1><p class="lead">${d.text}</p><div class="story-card">${d.card}</div><div class="story-question">${d.q}</div></section>`;document.getElementById("back").style.visibility=step?"visible":"hidden";if(window.CDSLang) window.CDSLang.translate(document.body);document.getElementById("next").textContent=step===data.length-1?"Explorer la simulation →":"Continuer →";if(step===data.length-1)document.getElementById("next").onclick=()=>location.href="demo.html";else document.getElementById("next").onclick=()=>{step++;render()}}
document.getElementById("back").onclick=()=>{if(step){step--;render()}};render();
