(() => {
const stages=[
{fr:'Le contexte',en:'The context',titleFr:'Amina entre dans une situation réelle.',titleEn:'Amina enters a real situation.',bodyFr:'Une organisation locale prépare une activité pour 40 jeunes. Les ressources sont limitées et le délai est de 10 jours.',bodyEn:'A local organization is preparing an activity for 40 young people. Resources are limited and the deadline is 10 days.',qFr:'Avant de parler de compétence, que savons-nous du contexte ?',qEn:'Before talking about skills, what do we know about the context?'},
{fr:'Le défi',en:'The challenge',titleFr:'Un problème réel est formulé.',titleEn:'A real problem is defined.',bodyFr:'TalentBridge demande à Amina de coordonner le déroulement, les participants et le lieu. Les critères observables sont définis avant l’action.',bodyEn:'TalentBridge asks Amina to coordinate the activity, participants and venue. Observable criteria are defined before action.',qFr:'Le système ne demande pas à Amina de prétendre être compétente : il lui donne une situation dans laquelle agir.',qEn:'The system does not ask Amina to claim competence: it gives her a situation in which to act.'},
{fr:'La première action',en:'The first action',titleFr:'Amina définit un plan et agit.',titleEn:'Amina defines a plan and acts.',bodyFr:'Elle répartit les rôles, contacte les participants et prépare le déroulement. Elle documente aussi ce qui se passe réellement.',bodyEn:'She assigns roles, contacts participants and prepares the activity. She also documents what actually happens.',qFr:'Ce qui compte ici est l’action observée, pas une note.',qEn:'What matters here is the observed action, not a score.'},
{fr:'L’itération',en:'The iteration',titleFr:'La première tentative est partielle.',titleEn:'The first attempt is partial.',bodyFr:'Deux intervenants se désistent. Amina réorganise le planning et répartit autrement les tâches. L’échec devient une information pour la suite.',bodyEn:'Two participants drop out. Amina reorganizes the schedule and redistributes tasks. The setback becomes information for what comes next.',qFr:'Une tentative partielle n’a pas besoin de devenir une étiquette sur la personne.',qEn:'A partial attempt does not need to become a label attached to the person.'},
{fr:'La réalisation',en:'The realization',titleFr:'Ce qui a réellement été accompli est documenté.',titleEn:'What was actually accomplished is documented.',bodyFr:'L’activité se déroule avec 36 participants. Amina a adapté le planning, coordonné trois personnes et produit le compte rendu de l’activité.',bodyEn:'The activity takes place with 36 participants. Amina adapted the schedule, coordinated three people and produced the activity report.',qFr:'On passe de « je sais organiser » à « voici ce que j’ai réalisé dans cette situation ».',qEn:'We move from “I can organize” to “here is what I accomplished in this situation”.'},
{fr:'La preuve',en:'The evidence',titleFr:'Une trace est reliée à la réalisation.',titleEn:'A trace is linked to the realization.',bodyFr:'Le compte rendu, le planning final et la liste de présence sont associés à la réalisation. Ils permettent de vérifier certains éléments précis.',bodyEn:'The report, final schedule and attendance list are linked to the realization. They make specific elements verifiable.',qFr:'Une preuve ne prouve pas tout. Elle permet de vérifier quelque chose de précis.',qEn:'Evidence does not prove everything. It makes something specific verifiable.'},
{fr:'Le témoignage',en:'The testimony',titleFr:'Paul confirme ce qu’il a réellement observé.',titleEn:'Paul confirms what he actually observed.',bodyFr:'Paul, qui accompagnait Amina, confirme qu’elle a réorganisé les tâches après le désistement et coordonné l’équipe. Il ne donne pas une note à Amina.',bodyEn:'Paul, who supported Amina, confirms that she reorganized tasks after the dropouts and coordinated the team. He does not give Amina a score.',qFr:'Le témoignage est limité au périmètre réel du témoin.',qEn:'Testimony is limited to the witness’s actual scope.'},
{fr:'Le partage et la décision',en:'Sharing and decision',titleFr:'Amina choisit ce qu’elle partage.',titleEn:'Amina chooses what she shares.',bodyFr:'Elle autorise une entreprise à voir le contexte, la réalisation, certaines preuves et le témoignage. L’entreprise peut alors proposer une opportunité.',bodyEn:'She allows a company to see the context, realization, selected evidence and testimony. The company can then propose an opportunity.',qFr:'CDS ne décide pas de la valeur d’Amina. Il rend l’expérience plus compréhensible pour une décision.',qEn:'CDS does not decide Amina’s value. It makes the experience more understandable for a decision.'}
];
let i=0;const root=document.getElementById('story');const counter=document.getElementById('counter');
function L(fr,en){return window.CDS_t?window.CDS_t(fr,en):fr}
function visual(){const labels=[['01','Situation'],['02','Défi'],['03','Action'],['04','Itération'],['05','Réalisation'],['06','Preuve'],['07','Témoignage'],['08','Partage']];const x=labels[i];return `<div class="story-visual" aria-hidden="true"><div class="story-visual-core"><b>${x[0]}</b><span>${L(x[1],x[1])}</span></div><i class="sv-orbit o1"></i><i class="sv-orbit o2"></i><i class="sv-dot d1"></i><i class="sv-dot d2"></i></div>`}
function render(){const s=stages[i];counter.textContent=String(i+1).padStart(2,'0')+' / '+String(stages.length).padStart(2,'0');root.innerHTML=`<section class="story-stage">${visual()}<div class="story-kicker">${L(s.fr,s.en)}</div><h1>${L(s.titleFr,s.titleEn)}</h1><p class="lead">${L(s.bodyFr,s.bodyEn)}</p><div class="story-card"><div class="person-line"><div class="initial">A</div><div><b>Amina · 19 ans</b><div class="muted">${L('Expérience fictive','Fictional experience')}</div></div></div><div class="story-question">${L(s.qFr,s.qEn)}</div></div></section>`;document.getElementById('prev').disabled=i===0;document.getElementById('next').textContent=i===stages.length-1?L('Ouvrir la simulation →','Open the simulation →'):L('Suivant →','Next →');window.CDS_apply?.(document)}
document.getElementById('prev').onclick=()=>{if(i>0){i--;render()}};document.getElementById('next').onclick=()=>{if(i<stages.length-1){i++;render()}else location.href='demo.html'};document.addEventListener('cds:language',render);render();
})();
